# Modified from https://github.com/Pranesh-2005/github-readme-stats-fast-action/blob/main/.github/workflows/update-readme-cards.yml
name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: Pranesh-2005/github-readme-stats-fast-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show=prs_merged&hide=stars&show_icons=true&theme=transparent&hide_border=true&rank_icon=github&custom_title=Stats%20for%20nerds
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate streak card
      #   uses: Pranesh-2005/github-readme-stats-fast-action@v1
      #   with:
      #     card: streak
      #     options: username=${{ github.repository_owner }}
      #     path: profile/streak.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate Top Languages card
      #   uses: Pranesh-2005/github-readme-stats-fast-action@v1
      #   with:
      #     card: top-langs
      #     options: username=${{ github.repository_owner }}
      #     path: profile/top-langs.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Generate Wakatime card
      #   uses: Pranesh-2005/github-readme-stats-fast-action@v1
      #   with:
      #     card: wakatime
      #     options: username=praneshjs
      #     path: profile/wakatime.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}
      

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add profile/*.svg
          git commit -m "Update README cards" || echo "No changes to commit"
          git push origin HEAD
